#!/bin/zsh

git diff
echo -n "Do you want to commit? (y/n): "
read confirmation
if [ "$confirmation" != "y" ]; then
    exit 0
fi
git add -A
git status

commitMessage="Updated $(($(date +'%Y') + 543))/$(date +'%m/%d %H:%M')"
git commit -m $commitMessage

echo -n "Do you want to push? (y/n): "
read confirmation
if [ "$confirmation" != "y" ]; then
    exit 0
fi
git push
